---
title: "4620_Report"
author: "Khaled Elhassan"
date: "2025-12-11"
output: 
      prettydoc::html_pretty:
        theme: cayman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(prettydoc)
```

# Overview
This report is an in-depth analysis of the well documented Ames Housing data. Initially, we conducted an exploratory data analysis (EDA) to become familiar with the specifics of the data, as well as to take note of any cleaning that may be needed for the following statistical analysis to work properly.  

Then, our group implemented $\text{four}$ different regression models and tested their efficacy: $\textbf{LASSO}$ and $\textbf{Ridge Regression}$ for ease of interpretation, $\textbf{Partial Least Squares}$ (PLS) to directly reduce the number of predictors, and a $\textbf{Regression Tree}$ for dealing with multi-collinearity among the predictors.  

Following that we used multiple measures of model performance to compare the effectiveness of each model to one another. We wanted to find out which model fits the Ames data the best, as well as what predictors said model found explain the most variability in the response, `SalePrice`. Finally, a short sensitivity analysis was done to assess how our model changes with different parameter values for the purpose of optimizing model performance.